name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-generators:
    if: github.event.commits[0].author.name != 'GitHubActions'
    name: Test
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [16.x]    

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        # with:
        #   token: ${{ secrets.PAT }}
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies globally
        # env:
        #   NODE_AUTH_TOKEN: $\{{ secrets.PAT }}
        run: |
          npm install
          npm install --global

      - name: Test generators
        run: npm run test:generators
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.json

      - name: Download previous test results
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test.yml
          branch: master
          name: test-results
          path: CICD_${{github.event.pull_request.head.sha}}
          workflow_conclusion: completed
      
      
      - name: Compare test results
        run: node CICD/compareTestResults test-results.json CICD_${{github.event.pull_request.head.sha}}/test-results.json

      - name: Update webpage contents
        if: github.event_name == 'push'
        run: node CICD/updateWebpage CICD_${{github.event.pull_request.head.sha}}/test-results.json 
      
      - name: Commit changes
        if: github.event_name == 'push'
        run: |
          git config --global user.name 'GitHubActions'
          git config --global user.email '<>'
          npm run format:write
          git add WEBPAGE.md
          git commit -m "docs: Auto-update WEBPAGE.md"
          git push

